name: "Backend release"

on:
  workflow_run:
    workflows: ["Tag Version"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    # run job only only if previous one was successful
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN2 }}
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          cd backend
          ./gradlew build publish  --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN2 }}
