name: docker login

on:
  workflow_call:
    inputs:
      docker_registry:
        description: 'The docker registry to use for docker login'
        required: false
        default: 'ghcr.io'
        type: string
      docker_user:
        description: 'The docker user to login'
        required: true
        type: string
    secrets:
      docker_password:
        description: 'The docker password for login'
        required: true

jobs:
  docker_release:
    name: docker release job
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.docker_password }}    
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.docker_registry }} 
          username: ${{ inputs.docker_user }} 
          password: ${{ secrets.docker_password }} 
