name: publish gradle project

on:
  workflow_call:
    inputs:
      project_dir:
        description: 'project dir with gradle file. current directory being default'
        required: false
        default: '.'
        type: string
      docker_registry:
        description: 'The docker registry to use for docker login'
        required: false
        default: 'ghcr.io'
        type: string
      docker_user:
        description: 'The docker user to login'
        required: true
        type: string
    secrets:
      checkout_token:
        description: 'workflow token for checkout and publish'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.checkout_token }}
      - name: Log in to the Container registryß
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.docker_registry }} 
          username: ${{ inputs.docker_user }} 
          password: ${{ secrets.docker_password }} 
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: |
          cd "${{ inputs.project_dir }}"
          ./gradlew build publish  --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.checkout_token }}
